# Generated by Django 5.2 on 2025-04-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
